const { contextBridge, ipcRenderer } = require('electron');

// Zpřístupnění specifických systémových funkcí pro frontend (index.html)
contextBridge.exposeInMainWorld('electronAPI', {
    exportDocx: (htmlContent, headerHtml, footerHtml) => ipcRenderer.invoke('export-docx', htmlContent, headerHtml, footerHtml),
    searchAres: (ico) => ipcRenderer.invoke('search-ares', ico),
    getTemplates: () => ipcRenderer.invoke('get-templates'),
    saveTemplate: (type, content) => ipcRenderer.invoke('save-template', type, content),
    resetTemplates: () => ipcRenderer.invoke('reset-templates'),
    getAppVersion: () => ipcRenderer.invoke('get-version'),
    onUpdateMessage: (callback) => ipcRenderer.on('update-message', (_event, value) => callback(value)),
    installUpdate: () => ipcRenderer.send('install-update'),
    exportBundle: (html, css, headerHtml, footerHtml, watermarkHtml) => ipcRenderer.invoke('export-bundle', html, css, headerHtml, footerHtml, watermarkHtml),
    saveIsdsConfig: (config) => ipcRenderer.invoke('save-isds-config', config),
    getIsdsConfig: () => ipcRenderer.invoke('get-isds-config'),
    savePostConfig: (config) => ipcRenderer.invoke('save-post-config', config),
    getPostConfig: () => ipcRenderer.invoke('get-post-config'),
    testIsdsConnection: (creds) => ipcRenderer.invoke('test-isds-connection', creds),
    isdsFindDataBox: (creds, query) => ipcRenderer.invoke('isds-find-databox', creds, query),
    isdsSendMessage: (creds, message) => ipcRenderer.invoke('isds-send-message', creds, message),
    isdsGetDeliveryInfo: (creds, dmID) => ipcRenderer.invoke('isds-get-delivery-info', creds, dmID),
    isdsOutboxEnqueue: (recipients, payload) => ipcRenderer.invoke('isds-outbox-enqueue', recipients, payload),
    isdsOutboxList: () => ipcRenderer.invoke('isds-outbox-list'),
    isdsOutboxRetry: (id) => ipcRenderer.invoke('isds-outbox-retry', id),
    isdsOutboxRefreshStatus: (fromTime) => ipcRenderer.invoke('isds-outbox-refresh-status', fromTime),
    onIsdsOutboxChanged: (callback) => ipcRenderer.on('isds-outbox-changed', () => callback()),
    renderPdfBase64: (html, css, headerHtml, footerHtml) => ipcRenderer.invoke('render-pdf-base64', html, css, headerHtml, footerHtml),
    openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
    calendarOpenIcs: (ics, name) => ipcRenderer.invoke('calendar-open-ics', ics, name),
    calendarSaveIcs: (ics, name) => ipcRenderer.invoke('calendar-save-ics', ics, name),
    isdsInboxRefresh: (mode, fromTime) => ipcRenderer.invoke('isds-inbox-refresh', mode, fromTime),
    isdsInboxList: () => ipcRenderer.invoke('isds-inbox-list'),
    isdsInboxDownload: (dmID) => ipcRenderer.invoke('isds-inbox-download', dmID),
    isdsInboxOpenFile: (filePath) => ipcRenderer.invoke('isds-inbox-open-file', filePath),
    isdsInboxMarkDeadline: (dmID) => ipcRenderer.invoke('isds-inbox-mark-deadline', dmID),
    testPostConnection: (creds) => ipcRenderer.invoke('test-post-connection', creds),
    authenticateBiometric: (reason) => ipcRenderer.invoke('authenticate-biometric', reason),
    importPdf: () => ipcRenderer.invoke('import-pdf'),
    importZfo: (filePath) => ipcRenderer.invoke('import-zfo', filePath),
    importPdfBase64: (base64) => ipcRenderer.invoke('import-pdf-base64', base64),
    saveAIConfig: (config) => ipcRenderer.invoke('save-ai-config', config),
    getAIConfig: () => ipcRenderer.invoke('get-ai-config'),
    startLexisLink: () => ipcRenderer.invoke('start-lexis-link'),
    queryInfoJednani: (params) => ipcRenderer.invoke('query-infojednani', params),
    onLexisLinkCommand: (callback) => ipcRenderer.on('lexis-link-command', (event, cmd) => callback(cmd)),
    onLexisConnectImport: (callback) => ipcRenderer.on('lexis-connect-import', (event, data) => callback(data)),
    onLexisLinkScan: (callback) => ipcRenderer.on('lexis-link-scan', (event, base64) => callback(base64)),
    // --- SECURITY LOCK ---
    lockSaveConfig: (config) => ipcRenderer.invoke('lock-save-config', config),
    lockGetConfig: () => ipcRenderer.invoke('lock-get-config'),
    lockDeleteConfig: () => ipcRenderer.invoke('lock-delete-config'),
    lockVerifyPassword: (password) => ipcRenderer.invoke('lock-verify-password', password),
    lockTouchIdAvailable: () => ipcRenderer.invoke('lock-touchid-available'),
});
