const { contextBridge, ipcRenderer } = require('electron');

// Zpřístupnění specifických systémových funkcí pro frontend (index.html)
contextBridge.exposeInMainWorld('electronAPI', {
    exportDocx: (htmlContent, headerHtml, footerHtml) => ipcRenderer.invoke('export-docx', htmlContent, headerHtml, footerHtml),
    // Word-parita: chytrý export — pro dokumenty s poznámkami / sledovanými změnami /
    // obsahem použije nativní OOXML cestu (docx), jinak html-to-docx. Import z Wordu
    // se zachováním revizí a poznámek pod čarou.
    exportDocxV2: (payload) => ipcRenderer.invoke('export-docx-v2', payload),
    importDocxNative: (arrayBuffer) => ipcRenderer.invoke('import-docx-native', arrayBuffer),
    docxExtractText: (arrayBuffer) => ipcRenderer.invoke('docx-extract-text', arrayBuffer),
    searchAres: (ico) => ipcRenderer.invoke('search-ares', ico),
    getTemplates: () => ipcRenderer.invoke('get-templates'),
    saveTemplate: (type, content) => ipcRenderer.invoke('save-template', type, content),
    resetTemplates: () => ipcRenderer.invoke('reset-templates'),
    getAppVersion: () => ipcRenderer.invoke('get-version'),
    onUpdateMessage: (callback) => ipcRenderer.on('update-message', (_event, value) => callback(value)),
    installUpdate: () => ipcRenderer.send('install-update'),
    exportBundle: (html, css, headerHtml, footerHtml, watermarkHtml) => ipcRenderer.invoke('export-bundle', html, css, headerHtml, footerHtml, watermarkHtml),
    saveIsdsConfig: (config) => ipcRenderer.invoke('save-isds-config', config),
    getIsdsConfig: () => ipcRenderer.invoke('get-isds-config'),
    savePostConfig: (config) => ipcRenderer.invoke('save-post-config', config),
    getPostConfig: () => ipcRenderer.invoke('get-post-config'),
    testIsdsConnection: (creds) => ipcRenderer.invoke('test-isds-connection', creds),
    isdsFindDataBox: (creds, query) => ipcRenderer.invoke('isds-find-databox', creds, query),
    isdsSendMessage: (creds, message) => ipcRenderer.invoke('isds-send-message', creds, message),
    isdsGetDeliveryInfo: (creds, dmID) => ipcRenderer.invoke('isds-get-delivery-info', creds, dmID),
    isdsOutboxEnqueue: (recipients, payload) => ipcRenderer.invoke('isds-outbox-enqueue', recipients, payload),
    isdsOutboxList: () => ipcRenderer.invoke('isds-outbox-list'),
    isdsOutboxRetry: (id) => ipcRenderer.invoke('isds-outbox-retry', id),
    isdsOutboxRefreshStatus: (fromTime) => ipcRenderer.invoke('isds-outbox-refresh-status', fromTime),
    isdsSaveSignedDelivery: (dmID) => ipcRenderer.invoke('isds-save-signed-delivery', dmID),
    onIsdsOutboxChanged: (callback) => ipcRenderer.on('isds-outbox-changed', () => callback()),
    renderPdfBase64: (html, css, headerHtml, footerHtml) => ipcRenderer.invoke('render-pdf-base64', html, css, headerHtml, footerHtml),
    openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
    calendarOpenIcs: (ics, name) => ipcRenderer.invoke('calendar-open-ics', ics, name),
    calendarSaveIcs: (ics, name) => ipcRenderer.invoke('calendar-save-ics', ics, name),
    isdsInboxRefresh: (mode, fromTime) => ipcRenderer.invoke('isds-inbox-refresh', mode, fromTime),
    pickCertificate: () => ipcRenderer.invoke('pick-certificate'),
    readDocxSpec: (filePath) => ipcRenderer.invoke('read-docx-spec', filePath),
    signPdf: (payload) => ipcRenderer.invoke('sign-pdf', payload),
    isdsInboxList: () => ipcRenderer.invoke('isds-inbox-list'),
    isdsInboxDownload: (dmID) => ipcRenderer.invoke('isds-inbox-download', dmID),
    isdsInboxOpenFile: (filePath) => ipcRenderer.invoke('isds-inbox-open-file', filePath),
    isdsInboxMarkDeadline: (dmID) => ipcRenderer.invoke('isds-inbox-mark-deadline', dmID),
    testPostConnection: (creds) => ipcRenderer.invoke('test-post-connection', creds),
    authenticateBiometric: (reason) => ipcRenderer.invoke('authenticate-biometric', reason),
    importPdf: () => ipcRenderer.invoke('import-pdf'),
    importZfo: (filePath) => ipcRenderer.invoke('import-zfo', filePath),
    importPdfBase64: (base64) => ipcRenderer.invoke('import-pdf-base64', base64),
    saveAIConfig: (config) => ipcRenderer.invoke('save-ai-config', config),
    getAIConfig: () => ipcRenderer.invoke('get-ai-config'),
    startLexisLink: () => ipcRenderer.invoke('start-lexis-link'),
    queryInfoJednani: (params) => ipcRenderer.invoke('query-infojednani', params),
    onLexisLinkCommand: (callback) => ipcRenderer.on('lexis-link-command', (event, cmd) => callback(cmd)),
    onLexisConnectImport: (callback) => ipcRenderer.on('lexis-connect-import', (event, data) => callback(data)),
    onLexisLinkScan: (callback) => ipcRenderer.on('lexis-link-scan', (event, base64) => callback(base64)),
    // --- SECURITY LOCK ---
    lockSaveConfig: (config) => ipcRenderer.invoke('lock-save-config', config),
    lockGetConfig: () => ipcRenderer.invoke('lock-get-config'),
    lockDeleteConfig: () => ipcRenderer.invoke('lock-delete-config'),
    lockVerifyPassword: (password) => ipcRenderer.invoke('lock-verify-password', password),
    lockTouchIdAvailable: () => ipcRenderer.invoke('lock-touchid-available'),
    // --- ZÁLOHA ŠIFROVACÍHO KLÍČE --- (main.js handlery existují, chyběl most →
    // funkce byla mrtvá a hrozila nevratná ztráta dat při ztrátě lexis.key)
    keyStatus: () => ipcRenderer.invoke('key-status'),
    keyBackup: () => ipcRenderer.invoke('key-backup'),
    keyRestore: () => ipcRenderer.invoke('key-restore'),
    // --- E-MAIL S PŘÍLOHOU přes nativního klienta ---
    composeEmailAttach: (opts) => ipcRenderer.invoke('compose-email-attach', opts),
    // --- ŠIFROVÁNÍ BLOBŮ pro localStorage at-rest (synchronní) ---
    secureEncrypt: (s) => { try { return ipcRenderer.sendSync('secure-encrypt-sync', s); } catch (e) { return null; } },
    secureDecrypt: (b) => { try { return ipcRenderer.sendSync('secure-decrypt-sync', b); } catch (e) { return null; } },
    // --- EXTRAKCE TEXTU Z PŘÍLOHY (PDF) pro náležitosti odpovědi ---
    extractFileText: (filePath) => ipcRenderer.invoke('extract-file-text', filePath),
    // --- KONTROLA PRAVOPISU (Chromium spellchecker) ---
    onSpellcheckContext: (callback) => ipcRenderer.on('spellcheck-context', (_e, data) => callback(data)),
    spellcheckReplace: (text) => ipcRenderer.invoke('spellcheck-replace', text),
    spellcheckAddWord: (word) => ipcRenderer.invoke('spellcheck-add-word', word),
    spellcheckSetEnabled: (enabled) => ipcRenderer.invoke('spellcheck-set-enabled', enabled),
    spellcheckStatus: () => ipcRenderer.invoke('spellcheck-status'),
});
